/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYBARRIER
#define MYBARRIER

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyBarrier : public RooAbsPdf {
public:
  MyBarrier() {} ; 
  MyBarrier(const char *name, const char *title,
	    RooAbsReal& _x,
	    RooAbsReal& _x0,
	    RooAbsReal& _width,
	    RooAbsReal& _sigma);
  MyBarrier(const MyBarrier& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyBarrier(*this,newname); }
  inline virtual ~MyBarrier() { }

  virtual Int_t getAnalyticalIntegral(RooArgSet& allVars, 
				      RooArgSet& analVars, const char* rangeName=0) const;
  virtual Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;

protected:

  RooRealProxy x ;
  RooRealProxy x0;
  RooRealProxy width;
  RooRealProxy sigma;
  
  Double_t evaluate() const ;


private:

  ClassDef(MyBarrier,1) // Your description goes here...
};
 
#endif
