/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef MYEXP
#define MYEXP

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class MyExp : public RooAbsPdf {
public:
  MyExp() {} ; 
  MyExp(const char *name, const char *title,
	      RooAbsReal& _x,
	RooAbsReal& _alpha,
	      RooAbsReal& _x0);
  MyExp(const MyExp& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new MyExp(*this,newname); }
  inline virtual ~MyExp() { }

  virtual Int_t getAnalyticalIntegral(RooArgSet& allVars, 
				      RooArgSet& analVars, const char* rangeName=0) const;
  virtual Double_t analyticalIntegral(Int_t code, const char* rangeName=0) const;

protected:

  RooRealProxy x ;
  RooRealProxy alpha ;
  RooRealProxy x0;
  
  Double_t evaluate() const ;


private:

  ClassDef(MyExp,1) // Your description goes here...
};
 
#endif
